
claude-api:
  api-key: ${CLAUDE_API_KEY}
  base-url: https://api.anthropic.com/v1/messages
server:
  port: 8080
replicate:
    token: ${REPLICATE_TOKEN}

spring:
  datasource:
    url: jdbc:h2:mem:testdb   # 메모리 모드
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true            # H2 콘솔 사용 가능
      path: /h2-console        # 접속 URL: http://localhost:8080/h2-console
  jpa:
    hibernate:
      ddl-auto: update          # 엔티티 기반으로 테이블 생성/업데이트
    show-sql: true              # 쿼리 로그 출력

cloud:
  aws:
    s3:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      region: ap-northeast-2 # 서울 리전 (원하는 리전으로 변경 가능)
      bucket: azit-bucket

fastapi:
  base-url: ${FASTAPI_URL:http://localhost:8000}